version: "3.1"

services:
    app:
        build: .
        command: sh -c "sleep 60 && npm run dev"
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - postgres
            - redis
        networks:
            - backend
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pindoramalearn?schema=public
    postgres:
        container_name: pindoramalearn
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: pindoramalearn
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - backend
    redis:
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - backend
        environment:
            REDIS_PASSWORD: redis
networks:
    backend:
        driver: bridge
