version: "3.1"

services:
    postgres:
        container_name: pindoramalearndb
        image: postgres:alpine
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: pindoramalearndb
        volumes:
            - ./data:/var/lib/postgresql/data
    app:
        build: .
        command: npm run dev
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
        depends_on:
            - postgres
        links:
            - postgres