version: "3.1"

services:
    postgres:
        container_name: pindoramalearn
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: pindoramalearn
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - backend
    app:
        build: .
        command: sh -c "sleep 10 && npm run dev"
        ports:
            - 3000:3000
        volumes:
            - .:/usr/app
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - backend
networks:
    backend:
        driver: bridge
